### ISSUE TITLE
Update to 1.7

### ISSUE THREAD

**Issue by maltokyo** [bobanilic/MerlinScale#3]
1.6.4 has some severe security issues, any possibility to update?  shame that the regular package isnt updated frequently

Thank you for mainlining this!

**Comment by bobanilic** [comment]
Connect on tailscale and run "tailscale update". This should start update process and update it to latest version! I'll update packages as soon as I can.

**Comment by maltokyo** [comment]
I just tried this and it works! Then why do you need to package one at all? ;) I'm very confused now. I thought the one they provided somehow wouldn't work

**Comment by bobanilic** [comment]
Glad u made it work. I had issues with main entware packages so I experimented and made it work

**Comment by santievil** [comment]
Doesnt work on armv5 or armv7 2.6. Any chances to get it updated?
